trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker login -u shashankbarsin -p $(password)
        docker build -f Dockerfile -t shashankbarsin/demo-app:1.0.0 .
        docker push shashankbarsin/demo-app:1.0.0