apiVersion : apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app 
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
        - name: demo-app
          image: shashankbarsin/demo-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
