on:
  push:
    branches:
      - main
  
jobs:      
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master    
      
    - uses: azure/k8s-set-context@users/shigupt/arc-set-context
      with:
        cluster-type: 'arc'
        creds: '${{ secrets.AZURE_CREDS }}'
        token: '${{ secrets.SA_TOKEN }}'
        resource-group: 'shiguptOnpremARC'
        cluster-name: 'onpremARCClus'    
                          
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml      
          manifests/namespace.yaml
